### ISSUE TITLE
shifting from empty non-pinned workspace to empty pinned workspace kills cosmic-session

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-workspaces-epoch#166]
```
pop 24.04 - 6.12.10-76061203

cosmic-session:
  Installed: 0.1.0~1744135980~24.04~be18d37

cosmic-comp:
  Installed: 0.1~1744406628~24.04~2f1873e
```

I created a pinned workspace (first workspace).

I then went to the newly created 2nd workspace (non-pinned). if the pinned workspace above it (pinned workspace 1) is empty (no windows or applications open in workspace) then cosmic session crashes.

steps to reproduce:
1 - Pin workspace 1 (make sure no applications/windows on workspace)
2 - move down to empty non-pinned workspace 2
3 - move back up to empty pinned workspace 1
4 - cosmic-session crash

see image attached to see the setup

![Image](https://github.com/user-attachments/assets/cf4bbfbb-b549-4b7b-809e-dc5e2e8623a1)
